# Generated by Django 5.2.3 on 2025-12-24 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminders', '0002_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='proof_image',
            field=models.ImageField(blank=True, null=True, upload_to='transaction_proofs/'),
        ),
    ]
