# Generated by Django 5.2.7 on 2025-12-27 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminders', '0004_customer_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='statement_pdf',
            field=models.FileField(blank=True, null=True, upload_to='statements/'),
        ),
    ]
