from reportlab.lib.pagesizes import A4
from reportlab.pdfgen import canvas
from django.conf import settings
import os


def generate_customer_statement(customer):
    file_name = f"statement_customer_{customer.id}.pdf"
    file_path = os.path.join(settings.MEDIA_ROOT, "statements", file_name)

    os.makedirs(os.path.dirname(file_path), exist_ok=True)

    c = canvas.Canvas(file_path, pagesize=A4)
    width, height = A4
    y = height - 50

    # ---------------- HEADER ----------------
    c.setFont("Helvetica-Bold", 16)
    c.drawString(50, y, "Customer Statement")
    y -= 30

    c.setFont("Helvetica", 11)
    c.drawString(50, y, f"Name: {customer.name}")
    y -= 18
    c.drawString(50, y, f"Phone: {customer.phone}")
    y -= 25

    # Outstanding balance
    last_txn = customer.transactions.order_by("-created_at").first()
    balance = last_txn.balance_after if last_txn else 0

    c.setFont("Helvetica-Bold", 12)
    c.drawString(50, y, f"Outstanding Balance: {balance}")
    y -= 30

    # ---------------- TABLE HEADER ----------------
    c.setFont("Helvetica-Bold", 10)
    c.drawString(50, y, "Date")
    c.drawString(130, y, "Type")
    c.drawString(200, y, "Amount")
    c.drawString(280, y, "Balance")
    c.drawString(360, y, "Proof")
    y -= 15

    c.line(50, y, 520, y)
    y -= 10

    # ---------------- TABLE ROWS ----------------
    c.setFont("Helvetica", 10)

    for txn in customer.transactions.order_by("created_at"):
        if y < 100:
            c.showPage()
            y = height - 50
            c.setFont("Helvetica", 10)

        c.drawString(50, y, txn.created_at.strftime("%d-%m-%Y"))
        c.drawString(130, y, txn.transaction_type.upper())
        c.drawString(200, y, str(txn.amount))
        c.drawString(280, y, str(txn.balance_after))

        # 🔗 CLICKABLE "VIEW PROOF"
        if txn.proof_image:
            proof_url = settings.MEDIA_URL + txn.proof_image.name
            full_url = settings.BASE_URL + proof_url if hasattr(settings, "BASE_URL") else proof_url

            c.setFillColorRGB(0, 0, 1)  # blue
            c.drawString(360, y, "View Proof")
            c.linkURL(full_url, (360, y - 2, 440, y + 10))
            c.setFillColorRGB(0, 0, 0)

        y -= 18

    # ---------------- FOOTER ----------------
    c.setFont("Helvetica-Oblique", 9)
    c.drawString(50, 40, "Generated by Ledgerly")

    c.save()

    customer.statement_pdf.name = f"statements/{file_name}"
    customer.save(update_fields=["statement_pdf"])

    return customer.statement_pdf.url
